[package]
name = "max_os"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
log = { path = "../libs/log" }
sdt = { path = "../libs/sdt" }
graphics = { path = "../libs/graphics" }
virtio = { path = "../libs/virtio" }
mmio = { path = "../libs/mmio" }
input = { path = "../libs/input" }
sync = { path = "../libs/sync" }
collections = { path = "../libs/collections" }
mem = { path = "../libs/mem" }

[[bin]]
name = "maxos"
path = "src/main.rs"
